### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by sRamosDev** [MrHaCkEr/webnovel2ebook#1]

**Comment by MrHaCkEr** [comment]
True. Never bothered to update the program. If somebody wants to write a similar program. You can just use this one and modify the scraping parameters

**Comment by sRamosDev** [comment]
Ok, thanks

**Comment by sRamosDev** [comment]
Are you using any framework?

**Comment by MrHaCkEr** [comment]
The code uses Selenium for browser automation, with phantomjs as a browser.

**Comment by sRamosDev** [comment]
Ok, I already fixed a few lines of code and now some of the novels are working. I pushed to my forked repository

**Comment by MrHaCkEr** [comment]
What novels are not working, which do work? What's the criteria?
Do you want me to refer to your fork on the Readme, or do you want to make a pull request?
I honestly doubt that I will manage this git repository because of a lack of interest and time.

**Comment by MrHaCkEr** [comment]
If you want to finish the program and you have any questions whatsoever, don't hesitate to ask me. For longer questions you can write me an E-Mail or we can talk over discord.
